# Generated by Django 2.2.6 on 2022-05-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220509_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('can_add_groups', 'Может добавлять группы'),), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
