# Generated by Django 2.2.6 on 2022-05-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220509_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('add_groups', 'Может добавлять группы'),), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
