# Generated by Django 2.2.16 on 2022-05-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220530_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
